### ISSUE TITLE
sc check allows broken installs of cfssl and cfssljson to pass

### ISSUE THREAD

**Issue by n3wscott** [GoogleCloudPlatform/k8s-service-catalog#99] opened 2017-12-21 19:29 UTC
I got:

```
⦿ sc check
Dependency check passed. You are good to go.
```

But had:

```
⦿ cfssl
Killed: 9
⦿ cfssljson
Killed: 9
```

So the binarys were broken but the sc check passed.

**Comment by martinmaly** [comment] 2018-01-29 21:26
Similar to #106, possibly a duplicate

**Comment by maqiuyujoyce** [comment] 2018-02-12 22:55
Confirmed that it is a duplicate of #106

**Closed by maqiuyujoyce** 2018-02-12 22:55 UTC
