### ISSUE TITLE
sc install fails on `clusterroles.rbac.authorization.k8s.io "etcd-operator" is forbidden`

### ISSUE THREAD

**Issue by squeedee** [GoogleCloudPlatform/k8s-service-catalog#91] opened 2017-12-05 17:17 UTC
I have a GKE cluster running 1.8.4 with legacy auth disabled
I have a cluster admin role. I prove that I have full access with
```bash
$ kubectl auth can-i '*' '*' --all-namespaces
yes
```

I run `sc install` and get the error `clusterroles.rbac.authorization.k8s.io "etcd-operator" is forbidden`

I don't know what I'm missing.

Role binding command:
```bash
$ kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=`gcloud config config-helper --format=json | jq '.configuration.properties.core.account'`
clusterrolebinding "cluster-admin-binding" created
```

Full output:
```bash
$ sc install
generated service catalog deployment config in dir: /tmp/service-catalog898278198
Service Catalog could not be installed
error deploying YAML files: deploy failed with output: exit status 1 :Error from server (Forbidden): error when creating "/tmp/service-catalog898278198/etcd-operator-rbac.yaml": clusterroles.rbac.authorization.k8s.io "etcd-operator" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["etcdclusters"], APIGroups:["etcd.database.coreos.com"], Verbs:["*"]} PolicyRule{Resources:["customresourcedefinitions"], APIGroups:["apiextensions.k8s.io"], Verbs:["*"]} PolicyRule{Resources:["storageclasses"], APIGroups:["storage.k8s.io"], Verbs:["*"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["*"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["*"]}] user=&{myemail@wherever.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
```

**Comment by squeedee** [comment] 2017-12-08 19:14
Just FYI, this does not happen on another GCP project, with an identically created cluster. IMHO there's a problem with rbac roles not being purely additive, although they should be.

**Comment by droot** [comment] 2017-12-08 19:20
Thanks for the update @squeedee 
Can you explain "there's a problem with rbac roles not being purely additive" a bit more ?

**Comment by droot** [comment] 2017-12-20 01:00
@squeedee debugged the issue. The problem is because of "extra" quotes in the username. using `jq` with `-r` option fixes the problem. You can examine current clusterrolebinding and see extra quote for the subject value. So correct command to create the clusterbinding would be:

$ kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=`gcloud config config-helper --format=json | jq -r '.configuration.properties.core.account'`

Pl. verify and close this bug if you get a chance. Thanks for reporting it.

**Closed** 2017-12-20 01:00 UTC
