### ISSUE TITLE
 sc add-gcp-broker fails. can't activate serviceregistry.googleapis.com

### ISSUE THREAD

**Issue by astraverkhau** [GoogleCloudPlatform/k8s-service-catalog#74] opened 2017-11-22 15:59 UTC
> Google Cloud Service Registry API has not been used in project ypcloud-io before or it is disabled.

can't find Google Cloud Service Registry API in the library and get 

> The API "serviceregistry.googleapis.com" doesn't exist or you don't have permission to access it

**Comment by automaticserver** [comment] 2018-01-03 17:23
Also stumbled onto this. According to https://support.google.com/a/answer/60757 you can only activate that API if you are logged in as the "Administrator" account, not your personal.

**Comment by amshuman-kr** [comment] 2018-01-15 12:21
I do not see "Google Cloud Service Registry API" in API Library. Is there a way to enable it?

**Comment by mihnjong** [comment] 2018-01-29 23:43
@quanjielin Could you help this bug?

**Comment by mihnjong** [comment] 2018-02-02 01:58
Sorry for the late reply. The API endpoint is private as of now, and you will be able to use it when it goes public. If you're interested in using it earlier, please ping me. I'll try to find a way to give you the access.

**Comment by mihnjong** [comment] 2018-02-02 02:00
Closing the bug now since it's expected behavior.

**Closed by mihnjong** 2018-02-02 02:00 UTC
